ci: ensure version is used as ref

diff --git a/.github/workflows/ci-cd-prod.yml b/.github/workflows/ci-cd-prod.yml
--- a/.github/workflows/ci-cd-prod.yml
+++ b/.github/workflows/ci-cd-prod.yml
@@ -1,14 +1,34 @@
 ﻿name: CI/CD Production
+description: Deploys the specified version to production
+run-name: CI/CD Production ${{ inputs.version && format('({0})', inputs.version) || '' }}
 
 on:
   workflow_dispatch:
-  
+    inputs:
+      version:
+        required: true
+        type: string
+
 concurrency:
-  group: ${{ github.workflow }}-${{ github.ref_name }}
+  group: ${{ github.workflow }}
 
 jobs:
+  check-if-version-exists:
+    name: Check if version exists
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if tag exists
+        run: |
+          if ! gh api repos/${{ github.repository }}/git/refs/tags/${{ inputs.version }} &>/dev/null; then
+            echo "::error::Version ${{ inputs.version }} does not exist as a tag"
+            exit 1
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   get-versions-from-github:
     name: Get Latest Deployed Version Info from GitHub
+    needs: [check-if-version-exists]
     uses: ./.github/workflows/workflow-get-latest-deployed-version-info-from-github.yml
     with:
       environment: prod
@@ -23,14 +43,10 @@ jobs:
       infra_base_sha: ${{ needs.get-versions-from-github.outputs.infra_version_sha }}
       apps_base_sha: ${{ needs.get-versions-from-github.outputs.apps_version_sha }}
 
-  get-current-version:
-    name: Get current version
-    uses: ./.github/workflows/workflow-get-current-version.yml
-
   deploy-infra:
     name: Deploy infra to prod
     if: ${{ github.event_name == 'workflow_dispatch' || needs.check-for-changes.outputs.hasInfraChanges == 'true' }}
-    needs: [get-current-version, check-for-changes]
+    needs: [check-for-changes]
     uses: ./.github/workflows/workflow-deploy-infra.yml
     secrets:
       AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
@@ -43,16 +59,16 @@ jobs:
     with:
       environment: prod
       region: norwayeast
-      version: ${{ needs.get-current-version.outputs.version }}
+      version: ${{ inputs.version }}
 
   store-infra-version:
     name: Store Latest Deployed Infra Version as GitHub Variable
-    needs: [deploy-infra, get-current-version]
+    needs: [deploy-infra]
     if: ${{ needs.deploy-infra.result == 'success' }}
     uses: ./.github/workflows/workflow-store-github-env-variable.yml
     with:
       variable_name: LATEST_DEPLOYED_INFRA_VERSION
-      variable_value: ${{ needs.get-current-version.outputs.version }}
+      variable_value: ${{ inputs.version }}
       environment: prod
     secrets:
       GH_TOKEN: ${{ secrets.RELEASE_VERSION_STORAGE_PAT }}
@@ -60,7 +76,7 @@ jobs:
   deploy-apps:
     name: Deploy apps to prod
     needs:
-      [get-current-version, check-for-changes]
+      [check-for-changes]
     if: ${{ github.event_name == 'workflow_dispatch' || needs.check-for-changes.outputs.hasBackendChanges == 'true' }}
     uses: ./.github/workflows/workflow-deploy-apps.yml
     secrets:
@@ -77,17 +93,17 @@ jobs:
     with:
       environment: prod
       region: norwayeast
-      version: ${{ needs.get-current-version.outputs.version }}
+      version: ${{ inputs.version }}
       runMigration: ${{ github.event_name == 'workflow_dispatch' || needs.check-for-changes.outputs.hasMigrationChanges == 'true' }}
 
   store-apps-version:
     name: Store Latest Deployed Apps Version as GitHub Variable
-    needs: [deploy-apps, get-current-version]
+    needs: [deploy-apps]
     if: ${{ always() && !failure() && (github.event_name == 'workflow_dispatch' || needs.deploy-apps.outputs.deployment_executed == 'true') }}
     uses: ./.github/workflows/workflow-store-github-env-variable.yml
     with:
       variable_name: LATEST_DEPLOYED_APPS_VERSION
-      variable_value: ${{ needs.get-current-version.outputs.version }}
+      variable_value: ${{ inputs.version }}
       environment: prod
     secrets:
       GH_TOKEN: ${{ secrets.RELEASE_VERSION_STORAGE_PAT }}
