Runs in k8s

diff --git a/.github/workflows/workflow-run-k6-performance.yml b/.github/workflows/workflow-run-k6-performance.yml
--- a/.github/workflows/workflow-run-k6-performance.yml
+++ b/.github/workflows/workflow-run-k6-performance.yml
@@ -18,6 +18,9 @@ on:
       duration:
         required: true
         type: string
+      parallelism:
+        required: true
+        type: number
     secrets:
       TOKEN_GENERATOR_USERNAME:
         required: true
@@ -33,14 +36,40 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
+    - name: OIDC Login to Azure Public Cloud
+      uses: azure/login@v2
+      with:
+        client-id: ${{ secrets.AZURE_CLIENT_ID }}
+        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+    - name: Populate kubeconfig with k6 context
+      id: populate_kubeconfig_with_k6_context
+      shell: bash
+      run: |
+        if ! az aks install-cli; then
+          echo "Failed to install kubectl CLI"
+          exit 1
+        fi
+
+        if ! az aks get-credentials --resource-group k6tests-rg --name k6tests-cluster; then
+          echo "Failed to populate kubeconfig"
+          exit 1
+        fi
+
+        if ! kubelogin convert-kubeconfig -l azurecli; then
+          echo "Failed to convert kubeconfig"
+          exit 1
+        fi
     - name: Setup k6
       uses: grafana/setup-k6-action@v1
     - name: Run K6 tests (${{ inputs.testSuitePath }})
       run: |
         echo "Running k6 test suite ${{ inputs.testSuitePath }} with ${{ inputs.vus }} VUs for ${{ inputs.duration }}"
-        k6 run ${{ inputs.testSuitePath }} --quiet --log-output=stdout --include-system-env-vars \
-          --vus=${{ inputs.vus }} --duration=${{ inputs.duration }} --out csv=./results.csv
-        grep http_req_duration ./results.csv | sort --field-separator=',' --key=3 -nr | head -10
+        # k6 run ${{ inputs.testSuitePath }} --quiet --log-output=stdout --include-system-env-vars \
+        #   --vus=${{ inputs.vus }} --duration=${{ inputs.duration }} --out csv=./results.csv
+
+        ./tests/k6/tests/scripts/run-test-in-k8s.sh -f ${{ inputs.testSuitePath }} -c k6-enduser-search -n k6-enduser-search -v ${{ inputs.vus }} -d ${{ inputs.duration }} -p ${{ inputs.parallelism }}
+        #grep http_req_duration ./results.csv | sort --field-separator=',' --key=3 -nr | head -10
       env:
         API_ENVIRONMENT: ${{ inputs.environment }}
         API_VERSION: ${{ inputs.apiVersion }}
